config/routes.rb
Rails.application.routes.draw do
  root 'foods#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
  }
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }

  resource :address, only: %i[new create show edit update]
  resource :cart, only: %i[show] do
    resources :cart_items, only: %i[create update destroy], module: :cart
  end
  resources :foods, only: %i[index show]
  resources :orders, only: %i[index new create show]
  resources :posts, only: %i[index new create edit update destroy] do
    resource :like, only: %i[create destroy], module: :posts
    resources :comments, only: %i[index new create edit update destroy], module: :posts
  end

  namespace :admin do
    root 'foods#index'
    resources :foods do
      member do
        patch :move_higher
        patch :move_lower
      end
    end
    resources :users, only: %i[index show edit update destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  scope :default_order, -> { order(id: :desc) }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :text, presence: true
  has_one_attached :image do |attachable|
    attachable.variant :display, resize_to_limit: [300, 300]
    attachable.variant :thumbnail, resize_to_limit: [200, 200]
  end
  scope :default_order, -> { order(id: :desc) }
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < Users::ApplicationController
  before_action :set_post
  before_action :set_comment, only: %i[edit update destroy]

  def index
    @comments = @post.comments
                     .default_order
                     .page(params[:page])
  end

  def new
    @comment = current_user.comments.new
  end

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to root_path, notice: 'コメントしました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to root_path, notice: 'コメントを編集しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy!
    redirect_to root_path, alert: 'コメントを削除しました', status: :see_other
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = current_user.comments.find_by(post: @post)
  end

  def comment_params
    params.require(:comment).permit(:text).merge(post: @post)
  end
end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < Users::ApplicationController
  before_action :set_post

  def create
    current_user.likes.create!(post: @post)
    LikeMailer.like_confirmation(@post).deliver_later
    redirect_to root_path, notice: 'Goodしました'
  end

  def destroy
    @like = current_user.likes.find_by(post: @post)
    @like.destroy!
    redirect_to root_path, alert: 'Goodを取り消しました', status: :see_other
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < Users::ApplicationController
  before_action :set_post, only: %i[edit update destroy]

  def index
    @posts = Post.default_order
                 .preload(:likes, :comments)
                 .with_attached_image
                 .page(params[:page])
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path, notice: '新規追加しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: '変更しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy!
    redirect_to root_path, alert: '削除しました', status: :see_other
  end

  private

  def set_post
    @post = current_user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text, :image)
  end
end

app/views/posts/comments/_form.html.haml
- url = comment.new_record? ? post_comments_path(post) : post_comment_path(post, comment)
- method = comment.new_record? ? :post : :patch

= simple_form_for(comment, url: url, method: method) do |f|
  = render 'admin/layouts/error', resource: comment
  = f.input :text
  = f.button :submit, class: "btn btn-outline-success my-4"

app/views/posts/comments/edit.html.haml
.container
  = render 'form', comment: @comment, post: @post

app/views/posts/comments/index.html.haml
.container
  .fs-3.my-3 コメント一覧
  .row
    - @comments.each do |comment|
      .col-sm-4.mb-3.mb-sm-0
        .card.mb-4
          .card-body.ms-2
            .card-text.mx-3= comment.user.email
            .hstack.gap-3
              .card-text.mx-3= comment.text
              - if comment.user == current_user
                .card-text
                  = button_to post_comment_path(@post, comment), method: :delete, data: { turbo_confirm: "削除してよろしいですか？" } do
                    %i.fa-solid.fa-x
                .card-text
                  = link_to edit_post_comment_path(@post, comment) do
                    %i.fa-solid.fa-comment{'data-test-id': dom_id(@post, :comment)}
  = paginate @comments, theme: 'twitter-bootstrap-4'

app/views/posts/comments/new.html.haml
.container
  = render 'form', comment: @comment, post: @post