config/routes.rb
Rails.application.routes.draw do
  root 'foods#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
  }
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }

  resource :address, only: %i[new create show edit update]
  resource :cart, only: %i[show] do
    resources :cart_items, only: %i[create update destroy], module: :cart
  end
  resources :foods, only: %i[index show]
  resources :orders, only: %i[index new create show]
  resources :posts, only: %i[index new create edit update destroy] do
    resource :like, only: %i[create destroy], module: :posts
    resources :comments, only: %i[index new create edit update destroy], module: :posts
  end

  namespace :admin do
    root 'foods#index'
    resources :foods do
      member do
        patch :move_higher
        patch :move_lower
      end
    end
    resources :users, only: %i[index show edit update destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :foods, through: :cart_items

  def subtotal
    cart_items.sum(&:price_including_tax).floor
  end

  def total_price_including_tax
    self.subtotal + ((self.cash_on_delivery_fee + self.shipping_fee) * Food::TAX_RATE)
  end

  def cash_on_delivery_fee
    case self.subtotal
    when 0...10000
      300
    when 10000...30000
      400
    when 30000...100000
      600
    else
      1000
    end
  end

  def total_cart_items_quantity
    cart_items.sum(&:quantity)
  end

  def shipping_fee
    unit_of_item = (self.total_cart_items_quantity / 5).ceil
    additional_fee = unit_of_item * 600
    600 + additional_fee
  end

  def orderable?
    cart_items.present? && cart_items.all?(&:orderable?)
  end
end

app/controllers/cart/cart_items_controller.rb
class Cart::CartItemsController < Users::ApplicationController
  before_action :set_cart_item, only: %i[update destroy]

  def create
    @cart_item = current_cart.cart_items.find_or_initialize_by(food_id: params[:food_id])
    @cart_item.increment(:quantity, params[:quantity].to_i)
    @cart_item.save!
    redirect_to cart_path, notice: 'カートに追加しました'
  end

  def update
    if @cart_item.update(cart_item_params)
      redirect_to cart_path, notice: '変更しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @cart_item.destroy!
    redirect_to cart_path, alert: '削除しました', status: :see_other
  end

  private

  def set_cart_item
    @cart_item = current_cart.cart_items.find(params[:id])
  end

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < Users::ApplicationController
  def show; end
end

app/helpers/carts_helper.rb
module CartsHelper
  def subtotal_text
    number_to_currency(current_cart.subtotal).to_s
  end

  def total_cart_price_including_tax_text
    number_to_currency(current_cart.total_price_including_tax).to_s
  end

  def cashier_button
    if current_cart&.cart_items&.empty? || !current_cart&.orderable?
      button_tag 'レジに進む', class: 'btn btn-outline-success disabled'
    else
      link_to 'レジに進む', new_order_path, class: 'btn btn-outline-success'
    end
  end

  def total_cart_items_quantity_text
    "#{current_cart.total_cart_items_quantity}個"
  end

  def shipping_fee_text
    number_to_currency(current_cart.shipping_fee).to_s
  end

  def cash_on_delivery_fee_text
    number_to_currency(current_cart.cash_on_delivery_fee).to_s
  end
end

app/views/carts/show.html.haml
.container
  .fs-2.page-title カート内商品
  %table.table.table-sm.w-75.mx-5.table-background{'data-test-id': dom_id(current_cart)}
    %thead
      %tr
        %th
        %th
        %th
        %th
        %th
        %th
    - current_cart.cart_items.adding_order.each do |item|
      %tbody
        %tr
          %th.align-middle.text-center{scope:"row"}= item.food.id
          %td.text-end
            = render 'shared/image', resource: item.food, size: "100x60"
          %td.align-middle.text-center.fs-5= item.food.name
          %td.align-middle.text-end= number_to_currency(item.price_including_tax)
          %td.align-middle.text-end
            = render "cart_items/edit_cart_form", cart_item: item
          %td.align-middle
            = button_to "削除する", cart_cart_item_path(item), method: :delete, class: "btn btn-success btn-sm", data: { turbo_method: "delete", turbo_confirm: "削除してよろしいですか？" }
          - unless item.orderable?
            %td.align-middle.text-danger.fw-bold= "注文不可の商品です"
    %tfoot
      %tr
        %th.align-middle.text-end{colspan:5} 合計点数
        %th.align-middle.text-center= total_cart_items_quantity_text
      - if current_cart.orderable?
        %tr
          %th.align-middle.text-end{colspan:5} 小計（税込）
          %th.align-middle.text-center= subtotal_text
        %tr
          %th.align-middle.text-end{colspan:5} 送料
          %th.align-middle.text-center= shipping_fee_text
        %tr
          %th.align-middle.text-end{colspan:5} 代引き手数料
          %th.align-middle.text-center= cash_on_delivery_fee_text
        %tr
          %th.align-middle.text-end{colspan:5} 合計（税込）
          %th.align-middle.text-center= total_cart_price_including_tax_text
  .d-flex.justify-content-end.my-5= cashier_button