config/routes.rb
Rails.application.routes.draw do
  root 'foods#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
  }
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }

  resource :address, only: %i[new create show edit update]
  resource :cart, only: %i[show] do
    resources :cart_items, only: %i[create update destroy], module: :cart
  end
  resources :foods, only: %i[index show]
  resources :orders, only: %i[index new create show]
  resources :posts, only: %i[index new create edit update destroy] do
    resource :like, only: %i[create destroy], module: :posts
    resources :comments, only: %i[index new create edit update destroy], module: :posts
  end

  namespace :admin do
    root 'foods#index'
    resources :foods do
      member do
        patch :move_higher
        patch :move_lower
      end
    end
    resources :users, only: %i[index show edit update destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :text, presence: true
  has_one_attached :image do |attachable|
    attachable.variant :display, resize_to_limit: [300, 300]
    attachable.variant :thumbnail, resize_to_limit: [200, 200]
  end
  scope :default_order, -> { order(id: :desc) }
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < Users::ApplicationController
  before_action :set_post
  before_action :set_comment, only: %i[edit update destroy]

  def index
    @comments = @post.comments
                     .default_order
                     .page(params[:page])
  end

  def new
    @comment = current_user.comments.new
  end

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to root_path, notice: 'コメントしました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to root_path, notice: 'コメントを編集しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy!
    redirect_to root_path, alert: 'コメントを削除しました', status: :see_other
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = current_user.comments.find_by(post: @post)
  end

  def comment_params
    params.require(:comment).permit(:text).merge(post: @post)
  end
end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < Users::ApplicationController
  before_action :set_post

  def create
    current_user.likes.create!(post: @post)
    LikeMailer.like_confirmation(@post).deliver_later
    redirect_to root_path, notice: 'Goodしました'
  end

  def destroy
    @like = current_user.likes.find_by(post: @post)
    @like.destroy!
    redirect_to root_path, alert: 'Goodを取り消しました', status: :see_other
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < Users::ApplicationController
  before_action :set_post, only: %i[edit update destroy]

  def index
    @posts = Post.default_order
                 .preload(:likes, :comments)
                 .with_attached_image
                 .page(params[:page])
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path, notice: '新規追加しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: '変更しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy!
    redirect_to root_path, alert: '削除しました', status: :see_other
  end

  private

  def set_post
    @post = current_user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text, :image)
  end
end

app/views/posts/_comment.html.haml
- if not post.user == current_user
  = link_to post_comments_path(post) do
    %i.fa-solid.fa-comment{'data-test-id': dom_id(post, :comment)}
    = "コメントを見る"
  = link_to new_post_comment_path(post) do
    %i.fa-regular.fa-comment{'data-test-id': dom_id(post, :comment)}
    = "コメントを書く"
- else
  = link_to post_comments_path(post) do
    %i.fa-solid.fa-comment
    = "コメントを見る"

app/views/posts/_form.html.haml
- url = post.new_record? ? posts_path : post_path(post)
- method = post.new_record? ? :post : :patch

= simple_form_for(post, url: url, method: method) do |f|
  = render 'admin/layouts/error', resource: post
  = f.input :title
  = f.input :text, input_html: {rows: 10}
  = f.file_field :image, accept: "image/jpeg,image/gif,image/png", class: 'form-control', direct_upload: true
  = f.button :submit, class: "btn btn-outline-success my-4"

app/views/posts/_like.html.haml
- if not post.user == current_user
  - if like
    = button_to post_like_path(post), class: "like-btn", method: :delete do
      %i.fa-solid.fa-thumbs-up{'data-test-id': dom_id(post, :like)}
      = "Good"
      = post.likes.count
  - else
    = button_to post_like_path(post), method: :post, class: "like-btn" do
      %i.fa-regular.fa-thumbs-up{'data-test-id': dom_id(post, :like)}
      = "Good"
      = post.likes.count
- else
  %i.fa-regular.fa-thumbs-up
  = "Good"
  = post.likes.count

app/views/posts/edit.html.haml
.container
  .fs-2.page-title 日記編集
  = render 'form', post: @post

app/views/posts/index.html.haml
.container
  .row
    - @posts.each do |post|
      .col-sm-8.mb-3.mb-sm-0
        .card.mb-4{'data-test-id': dom_id(post)}
          .card-body.ms-2
            .fs-5.card-title.mx-3.fw-semibold= post.title
            .hstack
              .card-text.ms-3= l post.created_at
              .card-text.ms-3= mail_to(post.user.email)
            .fs-6.card-text.mx-3.my-3= post.text
            .mx-3
              = render "shared/image", resource: post, size: "200x120"
            - if post.user == current_user
              .hstack.my-2
                .fs-6.card-text.ms-3= link_to "編集", edit_post_path(post)
                .fs-6.card-text.ms-3= button_to "削除", post_path(post), method: :delete, data: { turbo_confirm: "本当に削除しますか？" } , class: "nav-link link-danger"
            .mx-3.my-2
              .hstack.gap-3
                = render "like", post: post, like: current_user.likes.find_by(post_id: post.id)
                = render "comment", post: post, comment: current_user.comments.find_by(post_id: post.id)
  = paginate @posts, theme: 'twitter-bootstrap-4'

app/views/posts/new.html.haml
.container
  .fs-2.page-title 日記新規作成
  = render 'form', post: @post