config/routes.rb
Rails.application.routes.draw do
  root 'foods#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
  }
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }

  resource :address, only: %i[new create show edit update]
  resource :cart, only: %i[show] do
    resources :cart_items, only: %i[create update destroy], module: :cart
  end
  resources :foods, only: %i[index show]
  resources :orders, only: %i[index new create show]
  resources :posts, only: %i[index new create edit update destroy] do
    resource :like, only: %i[create destroy], module: :posts
    resources :comments, only: %i[index new create edit update destroy], module: :posts
  end

  namespace :admin do
    root 'foods#index'
    resources :foods do
      member do
        patch :move_higher
        patch :move_lower
      end
    end
    resources :users, only: %i[index show edit update destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/views/admin/layouts/_flash.html.haml
.container
  - if flash['notice'].present?
    .alert.alert-success
      = notice
  - elsif flash['alert'].present?
    .alert.alert-danger
      = alert

app/views/admin/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.border-bottom.mb-4.justify-content-md-between
  .container
    = link_to 'sakura_market 管理画面', admin_root_path, id: "logo"
    %ul.nav.nav-pills
      - if admin_signed_in?
        %li.nav-item
          = link_to "商品新規作成", new_admin_food_path, class: "nav-link"
        %li.nav-item
          = link_to "ユーザー一覧", admin_users_path, class: "nav-link"
        %li.nav-item
          = button_to '管理者ログアウト', destroy_admin_session_path, method: :delete, class: "nav-link"
      - else
        %li.nav-item
          = link_to 'ログイン', new_admin_session_path